### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by squidfunk**
This PR adds TypeScript typings.

### CODE REVIEW

**Comment by squidfunk** [comment]
The npm package did not include the typings, as the `package.json` only defined a `files` array. I pointed `main` to `index.js` and added `index.d.ts` to `files` which fixes the issue.

**Comment by wooorm** [comment]
Thanks for taking the initiative to work on this!

[TypeScript recommends types for non-TS packages to be published from DefinitelyTyped](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

What is the reason for going against their advice?

**Comment by squidfunk** [comment]
Honestly, I object this, as separating typings from their source may induce lag and drift. Many typings that are on DefinitelyTyped, especially those for lesser-known, smaller libraries are old and incorrect as they are not updated. From my experience, placing the typings next to the source yields more up-to-date typings and greatly improves the ease of maintenance.

I, myself, have a library for which someone wrote DefinitelyTyped typings and those typings are outdated and wrong. This recommendation feels dated and probably comes from a time where there weren't many typings and the TypeScript team wanted everyone to benefit.

**Comment by wooorm** [comment]
> Honestly, I object this, as separating typings from their source may induce lag and drift. Many typings that are on DefinitelyTyped, especially those for lesser-known, smaller libraries are old and incorrect as they are not updated. From my experience, placing the typings next to the source yields more up-to-date typings and greatly improves the ease of maintenance.

Yes, that is a downside, but I don’t use typescript. And people contributing here may not either. Meaning that the types here will also lag and drift apart.

> I, myself, have a library for which someone wrote DefinitelyTyped typings and those typings are outdated and wrong.

It’s open source! Anyone can contribute to DT!

> This recommendation feels dated and probably comes from a time where there weren't many typings and the TypeScript team wanted everyone to benefit.

I cannot speak to their opinions. But I did “survive the coffeescript era”, which was similar: maintainers got pull requests rewriting their projects into CS or did it themselves, and a couple years later, everyone reverted again.
The projects I maintain, although this one is really new, have been around since I started OSS 6 years ago, and will be around for the next 6 as well.
If you’d like to sign up to maintain the TS definitions here for say, the foreseeable future of a couple of years, I’m fine adding them here, and I’ll give you write permissions!

**Comment by squidfunk** [comment]
> If you’d like to sign up to maintain the TS definitions here for say, the foreseeable future of a couple of years, I’m fine adding them here, and I’ll give you write permissions!

I would regard the API of this project (for which the typings are for) as rather stable, as the project implements an RFC spec and does not provide a super-hipster frontend framework. However, if you feel that it's not a good fit, feel free to close this PR. I will then just add the typings locally to my project, as I have a single location where I use your library (kudos for that btw.).

I have no intention to become a maintainer of this project or contribute to DefinitelyTyped, as the latter repository is absolutely unusable because of its sheer size. I just wanted to "give something back".

**Comment by wooorm** [comment]
Alright! I really appreciate that you want to contribute and help, but I’d rather not accept this change though, as outlined above. I think definitely typed is the place for it, and hope that you’d reconsider (or maybe raise the question whether the DT advise is still current with TS folks?)

Thanks and best!

**Comment by squidfunk** [comment]
Funny, that you accept typings to be included in the repository for [`unified`](https://github.com/unifiedjs/unified), but not for this one. But hey, nevermind.

**Comment by wooorm** [comment]
The reason for that is that a community maintains the unified collective. Several of the people there maintain the types. Although I created unified, and am a core maintainer, I am not the only voice there.

**Pull request closed without merging**
