### PR TITLE
Fix return type of `filter`

### LINKED ISSUE #3: Filter return type
Hey, I noticed that the return type defined here:

https://github.com/wooorm/bcp-47-match/blob/94c31cb95f2ed22a37714bd978952de19a2a1d13/index.js#L24

Is a single string for the `filter` type methods, but the readme and code suggest the actual return type is an Array aka `Tags`. Is there a piece I'm missing here? I'm glad to make a PR if you think it should be changed

### PR DESCRIPTION
**Pull request by jpasquers**
Fixes https://github.com/wooorm/bcp-47-match/issues/3

### CODE REVIEW

**Comment by wooorm** [comment]
Can you look at the tests?

**Comment by jpasquers** [comment]
> Can you look at the tests?

Yep I'm looking into it. Sorry been in on and off meetings but will have some time in a bit

**Comment by wooorm** [comment]
all the time in the world, no rush, and let me know if you have Qs!

**Comment by jpasquers** [comment]
So this led me down quite the rabbit hole. As far as I could tell the ts typing was failing even in main. There is some really tricky behavior surrounding the filter option dictating the return type of the inner `match` method. I reached a solution which is reasonable but probably overly complicated. An additional consequence of the new type declarations is the unintended export of things like `FilterOrLookup` and `FilterOrLookupResponse`

**Comment by jpasquers** [comment]
We can go forward with this, but I definitely understand if you would rather just reformat the code or have any other insights. I just wanted to avoid touching the real code if possible.

**Comment by jpasquers** [comment]
any update here?

**Review by wooorm — APPROVED** [review]
Thanks for your patience!

> As far as I could tell the ts typing was failing even in main

I see it, weird how that started happening 🤷‍♂️

> An additional consequence of the new type declarations is the unintended export of things like `FilterOrLookup` and `FilterOrLookupResponse`

This can be “solved” by moving everything to `lib/`, and explicitly choosing which types and identifiers to export from `index.js`.

> I just wanted to avoid touching the real code if possible.

:+1:

---

I’ll merge this, and will take a look at the code-style and what to export locally!

**Comment by wooorm** [comment]
Managed to remove a bunch of types that weren’t needed, and was able to get rid of the `prettier-ignore`: https://github.com/wooorm/bcp-47-match/commit/6d4a74b703a13e3828785ed9d67d59aa6a2153fe?w=1

**Comment by wooorm** [comment]
Thanks, released in 2.0.2!

**Pull request merged**
